[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    permissions-policy = "accelerometer=(), camera=(), geolocation=(), gyroscope=(), magnetometer=(), microphone=(), payment=(), usb=(), interest-cohort=()"
    referrer-policy = "strict-origin-when-cross-origin"