backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "category"
    label: "Kategorie"
    folder: "content/category"
    create: true
    slug: "index"
    media_folder: ""
    public_folder: ""
    path: "{{title}}/index"
    editor:
      preview: false
    fields:
      - { label: "Nazev", name: "title", widget: "string" }
      - { label: "Kratky popisek", name: "short", widget: "string" }
      - { label: "Popisek", name: "body", widget: "markdown" }
      - { label: "Obrazek", name: "image", widget: "image" }
      - { name: "type", widget: "hidden", default: "category" }
      - { label: "Id (nemenit)", name: "id", widget: "string" }
  - name: "krouzek"
    label: "Krouzek"
    folder: "content/krouzek"
    create: true
    slug: "index"
    media_folder: ""
    public_folder: ""
    path: "{{title}}/index"
    editor:
      preview: false
    fields:
      - { label: "Nazev", name: "title", widget: "string" }
      - { label: "Kratky popisek", name: "excerpt", widget: "string" }
      - { label: "Popisek", name: "body", widget: "markdown" }
      - { label: "Obrazek", name: "image", widget: "image" }
      - { name: "type", widget: "hidden", default: "krouzek" }
      - {
          name: "category",
          widget: "relation",
          collection: "category",
          search_fields: [title],
          value_field: id,
        }
      - {
          label: "Casy",
          name: times,
          widget: list,
          field:
            {
              name: time,
              widget: "object",
              fields:
                [
                  {
                    name: day,
                    widget: select,
                    options:
                      [
                        { label: Pondeli, value: monday },
                        { label: Utery, value: tuesday },
                        { label: Streda, value: wednesday },
                        { label: Ctvrtek, value: thursday },
                        { label: Patek, value: friday },
                        { label: Sobota, value: saturday },
                        { label: Nedele, value: sunday },
                      ],
                  },
                  {
                    name: start,
                    widget: datetime,
                    date_format: false,
                    time_format: "HH:mm",
                  },
                  {
                    name: end,
                    widget: datetime,
                    date_format: false,
                    time_format: "HH:mm",
                  },
                ],
            },
        }
